server.port=${PORT:8081}

sf.client-id=${SF_CLIENT_ID}
sf.client-secret=${SF_CLIENT_SECRET}
sf.redirect-uri=${SF_REDIRECT_URI}
sf.login-url=${SF_LOGIN_URL:https://login.salesforce.com}

app.frontend-url=${FRONTEND_URL}

server.servlet.session.timeout=86400s
spring.session.store-type=none
